CommitMsg:
  CapitalizedSubject:
    enabled: false

  EmptyMessage:
    enabled: false

  TrailingPeriod:
    enabled: true

  TextWidth:
    enabled: false

PreCommit:
  ALL:
    on_warn: fail

  AuthorEmail:
    enabled: true

  AuthorName:
    enabled: true

  MergeConflicts:
    enabled: true

  YamlSyntax:
    enabled: true

  BundleCheck:
    enabled: true

PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail # Treat all warnings as failures
    command: ['bundle', 'exec', 'rubocop']

  TrailingWhitespace:
    enabled: true
    exclude:
    - '**/db/structure.sql' # Ignore trailing whitespace in generated files

PostCheckout:
 ALL: # Special hook name that customizes all hooks of this type
   quiet: true # Change all post-checkout hooks to only display output on failure

 IndexTags:
   enabled: true # Generate a tags file with `ctags` each time HEAD changes
